### ISSUE TITLE
DropdownList country empty

### ISSUE THREAD

**Issue by allanzh** [PartnerCenterSamples/Reseller-Web-Application#49] opened 2017-09-05 13:29 UTC
Hi Everyone,

When I try to buy an item, I can't select my country. There are no Options in dropdown list as you can see on the image below.
![screenshot_4](https://user-images.githubusercontent.com/2539476/30063405-008f60b0-9225-11e7-8137-fcad31cd5af6.png)

**Comment by ParagMJoshi** [comment] 2017-09-05 22:51
Hello Allanzh

What is the Country of the Partner for which this is installed.

Regards
Parag.

**Comment by hsbsandrecv** [comment] 2017-09-05 23:16
Hello Parag,

Thank you for replying, I work with Allanzh in this Partner Storefront project. Partner country is Brazil (BR)
Regards,

Andre

**Comment by ParagMJoshi** [comment] 2017-09-06 00:01
Hello Andre, Allanzh,

Unfortunately Brazil is not supported country on CSP Customer Storefront Builder Quick Start Guide

https://msdn.microsoft.com/en-us/library/partnercenter/mt759509.aspx 

Thanks
Parag.

**Comment by allanzh** [comment] 2017-09-06 11:34
Hello @ParagMJoshi ,
As André said, our Partner Country is Brazil, we're sorry to hear that the country is not supported. 
Do you know if guys have plans to add Brazil in the roadmap? is that any way to make Storefront works in Countries who hasn't support?

**Comment by tameemansari** [comment] 2017-09-06 19:46
@allanzh . Your ask is valid. While we explore future roadmap cases to support additional regions for the storefront. The challenge is largely around the payment gateway provider in a given region. Not all regions / countries support PayPal as a recommended payment gateway. 

We can definitely collaborate with partners interested in extending the storefront code to build additional payment gateway providers specific to their region so that we can bring in support. 

Another option which you can explore is to setup the pre approved billing model for your storefront deployment and also include changes to display the country as your own custom changes. 

Adding additional countries in the create customer page drop down is fairly straightforward.
This will involve you adding items to the [select list viewModel variable](https://github.com/PartnerCenterSamples/Reseller-Web-Application/blob/master/Source/PartnerCenter.CustomerPortal/Scripts/Plugins/Views/NewCustomerProfileView.js#L33).

**Comment by allanzh** [comment] 2017-09-08 17:52
Thanks @tameemansari 
It's good to hear that me and @hsbsandrecv can collaborate with you, but right now we don't use any gateway in our company. So in our scenario we will just show one confirmation screen and our clients will be charged later.

We configure all customers as pre-approved and it works well.

About the Additional Coutry, I don't know if we are doing something wrong, but we put **case"BR"** into the code and dropdownlist are still empty.
![screenshot_6](https://user-images.githubusercontent.com/2539476/30224069-b43f6cec-94a3-11e7-9256-69c8ad24514d.png)

**Comment by tameemansari** [comment] 2017-09-08 19:03
@ParagMJoshi can help you with the code changes to add the additional country list.

**Comment by ParagMJoshi** [comment] 2017-09-08 19:28
Sure Tameem. Let me make the changes and Test it...

**Comment by ParagMJoshi** [comment] 2017-09-08 20:27
Hello Allanzh,
Please send a mail on v-paragj@microsoft.com so I can take it ahead. I will need some information so I can let you know the changes needed, Get it tested to completion.

Thanks
Parag

**Comment by allanzh** [comment] 2017-09-11 11:00
Hi @ParagMJoshi ,
I already sent it.

Thanks
Allan

**Comment by ParagMJoshi** [comment] 2017-09-11 20:04
Thanks Allan, I have replied to your mail from my official Microsoft ID. 
Once the issue is resolved we will close this issue.. till then we can communicate on my Microsoft ID.

thanks
Parag.

**Comment by tameemansari** [comment] 2017-09-19 18:09
Closing this item since the original issue on this thread is resolved. Please reopen in case this needs to be kept open.

**Closed by tameemansari** 2017-09-19 18:09 UTC
