### ISSUE TITLE
Upgrade caused errors

### ISSUE THREAD

**Issue by lukeryb** [PartnerCenterSamples/Reseller-Web-Application#29] opened 2017-01-13 16:48 UTC
Hi Team, 

After upgrading the web store front via CSP, we are not getting several errors. 

When loading the web page, we get "Could not retrieve the offers". 

If I login using my account, and I try to go through offers setup, I am un able too and get the following error "Could not retrieve Microsoft offers". 

Can you help? 

Thanks

**Comment by tameemansari** [comment] 2017-01-17 19:28
Sure @lukeryb. Will follow up over email and we can diagnose this issue. I suspect that some of the offers which were created prior to this release have been withdrawn and hence this issue is occurring. We can investigate further to identify root cause.

**Comment by sean-anr** [comment] 2017-02-14 13:42
I know I'm a little late to the conversation, but we're having the same issue.  Were you able to resolve it?

**Comment by tameemansari** [comment] 2017-02-14 21:22
Looks like this thread should be merged with the other issue - https://github.com/PartnerCenterSamples/Reseller-Web-Application/issues/33 

@sean-anr and @lukeryb can you please provide the names of your organizations so that I can look up your profile in the backend to investigate this issue further. 

I am closing this thread so that all the activity can be done against one GitHub issue. Thanks.

**Comment by tameemansari** [comment] 2017-02-14 21:22
#33

**Comment by lukeryb** [comment] 2017-02-14 21:23
360 Visibility Inc.

Thanks

On Feb 14, 2017 4:22 PM, Tameem Ansari <notifications@github.com> wrote:

Looks like this thread should be merged with the other issue - #33<https://github.com/PartnerCenterSamples/Reseller-Web-Application/issues/33>

@sean-anr<https://github.com/sean-anr> and @lukeryb<https://github.com/lukeryb> can you please provide the names of your organizations so that I can look up your profile in the backend to investigate this issue further.

I am closing this thread so that all the activity can be done against one GitHub issue. Thanks.

**Closed** 2017-02-14 21:23 UTC

**Comment by tameemansari** [comment] 2017-02-14 21:33
Thank you both. Much appreciated.

**Comment by tameemansari** [comment] 2017-02-15 22:15
@lukeryb. This issue is now resolved.
