### ISSUE TITLE
Locale not supported when getting offers

### ISSUE THREAD

**Issue by jasonflowers** [PartnerCenterSamples/Reseller-Web-Application#33] opened 2017-02-07 17:42 UTC
Hi. I have successfully deployed the solution through the Partner Center and whilst going through the configuration wizard on the site (within "Offers Setup") I get an error stating unable to retrieve offers. When I run a stream log on Azure I find the following stack trace "Locale: en-GB
Base Description: Microsoft.Store.PartnerCenter.Exceptions.PartnerException: Locale en-GB is not supported
   at Microsoft.Store.PartnerCenter.Network.PartnerServiceProxy`2.<HandleResponseAsync>d__60.MoveNext()
"
Is this a known limitation?

Regards,
Jason

**Comment by chpolania** [comment] 2017-02-10 20:44
hi, i have the same error Locale: es-CO
Base Description: Microsoft.Store.PartnerCenter.Exceptions.PartnerException: Locale es-CO is not supported

Thanks

**Comment by tameemansari** [comment] 2017-02-13 18:52
@jasonflowers and @chpolania ... can you please paste the complete stack trace.

**Comment by ravimandal47** [comment] 2017-02-14 07:03
Hi, I am facing the same issue. 

Here is the stack trace. 


```
Activated	Event	Time	Duration	Thread
	ErrorHandler: Intercepted Exception: Partner Exception:
Error Category: NotFound
Service Error Payload: 
Error code: 0
Error message: Locale ne-NP is not supported
Error data:


Context: Request Id: 5428b8d7-f3b3-4123-9245-61a094ace284, Correlation Id: c17e2838-f41a-483b-98fa-011b8112c221, Locale: ne-NP
Base Description: Microsoft.Store.PartnerCenter.Exceptions.PartnerException: Locale ne-NP is not supported
   at Microsoft.Store.PartnerCenter.Network.PartnerServiceProxy`2.<HandleResponseAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Store.PartnerCenter.Network.PartnerServiceProxy`2.<SendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Store.PartnerCenter.Network.PartnerServiceProxy`2.<GetAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Store.PartnerCenter.Offers.OfferCollectionOperations.<GetAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Store.PartnerCenter.CustomerPortal.BusinessLogic.Offers.PartnerOffersRepository.<RetrieveMicrosoftOffersAsync>d__5.MoveNext() in D:\Repo\Reseller-Web-Application\Source\PartnerCenter.CustomerPortal\BusinessLogic\Offers\PartnerOffersRepository.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Store.PartnerCenter.CustomerPortal.Controllers.AdminConsoleController.<GetMicrosoftOffers>d__7.MoveNext() in D:\Repo\Reseller-Web-Application\Source\PartnerCenter.CustomerPortal\Controllers\AdminConsoleController.cs:line 218
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
. Returning 500 as response.	30.52s		

```

**Comment by jasonflowers** [comment] 2017-02-14 11:28
Apologies for the delay but thanks to ravimandal47 for providing! :)

**Comment by tameemansari** [comment] 2017-02-14 21:19
Can some of you please provide your partner organization names so that I can look up your org profiles and the language setting you have due to which the API call may be failing.

**Comment by sean-anr** [comment] 2017-02-14 21:29
Org name: A&R Solutions

Thanks!

**Comment by ravimandal47** [comment] 2017-02-15 01:22
Organization Name: Unlimited Technology Pvt. Ltd. 
Tenant: unlimitednepal.onmicrosoft.com 

Thanks for the response.

**Comment by tameemansari** [comment] 2017-02-15 02:30
Thanks all. I have isolated the root cause. A fix should be available before Monday.

**Comment by ravimandal47** [comment] 2017-02-15 04:52
@tameemansari  is there any workaround available till the time a fix is released?

**Comment by tameemansari** [comment] 2017-02-15 05:30
@ravimandal47 unfortunately no workaround without a code change. The offer catalog on the server side (Partner Center) is explicitly looking for specific locales which it can return for localized offer names. The fix needs to consider the languages for which the web storefront is localized and set the locale accordingly for that call. In the case of ne-NP it would fallback to en-US, For other regions it would need to check the language in the locale and pick up on the corresponding one of the supported 42 languages in Partner Center else default to en-US. If I am able to spend adequate time on this tomorrow then I can go through the engineering loop for this one and get this out in the next 24hrs. Will try my best :).

**Comment by theciscokid1** [comment] 2017-02-15 07:08
Same issue with SG locale

**Comment by jasonflowers** [comment] 2017-02-15 08:16
Many Thanks for your efforts tameemansari!

**Comment by chpolania** [comment] 2017-02-15 18:31
Thanks friend!

**Comment by tameemansari** [comment] 2017-02-15 22:18
Folks from this thread and related threads who raised this issue. https://github.com/PartnerCenterSamples/Reseller-Web-Application/issues/29 and 
@jasonflowers, @chpolania, @ravimandal47, @sean-anr, @theciscokid. The fix is now merged to main. You can [upgrade from Partner Center](https://partnercenter.microsoft.com/en-us/pcv/webstore/preparedeployment) to deploy the fix. This will ensure that you don't need to go through setup again for other configurations like branding and payment. 

I will be closing this issue in a day or two once you get a chance to verify the fix.

**Comment by ravimandal47** [comment] 2017-02-16 05:32
Thanks @tameemansari it is working now. :)

**Comment by jasonflowers** [comment] 2017-02-16 15:09
Great work tameemansari - seems to working for me now too ! :)

**Comment by tameemansari** [comment] 2017-02-16 18:25
Thanks for confirming @ravimandal47 and @jasonflowers. I will close this issue.

**Closed by tameemansari** 2017-02-16 18:25 UTC
Labels: bug, question

**Comment by theciscokid1** [comment] 2017-02-17 01:49
@tameemansari We have managed to get it going but notice the country selection Singapore is not available, will this be added or can we add this ourselves? Can I aslo confirm the pricing that gets pulled across is USD when creating offers?

**Comment by ravimandal47** [comment] 2017-02-17 05:58
@tameemansari @theciscokid1  I am also facing the same issue. I cannot get Nepal in dropdown. How can I fix this?

**Comment by tameemansari** [comment] 2017-02-17 18:10
@theciscokid1 and @ravimandal47 can you please open new issues to track these questions. 

Nepal and Singapore were not part of the countries / regions we currently support. 
Adding additional countries in the create customer page drop down is fairly straightforward. 
This will involve you adding items to the [select list viewModel variable](https://github.com/PartnerCenterSamples/Reseller-Web-Application/blob/master/Source/PartnerCenter.CustomerPortal/Scripts/Plugins/Views/NewCustomerProfileView.js#L18). You can see how multiple items are managed for such a page by taking a look at the [Payment type drop down behavior](https://github.com/PartnerCenterSamples/Reseller-Web-Application/blob/master/Source/PartnerCenter.CustomerPortal/Scripts/Plugins/PaymentSetupPresenter.js#L18)

Pricing is set by the storefront admin. The currency is determined by the partner profile country default currency support in regional authorization. In case its unable to support the currency then it defaults the currency to USD.
